name: Build Fedora 42 Kernel from Fork

on:
  workflow_dispatch:
    inputs:
      fork_owner:
        description: 'Your GitHub username or organization that owns the fork'
        required: true
        default: 'op30mmd' # The default upstream kernel repository owner
      branch_name:
        description: 'The branch to build from your fork'
        required: true
        default: 'master' # The default upstream kernel branch

jobs:
  build:
    runs-on: ubuntu-latest
    container: fedora:42
    steps:
      - name: Install Build Dependencies
        run: |
          # CORRECTED: Added the 'bc' package required for the final RPM build stage.
          # Install all necessary tools for kernel compilation and packaging.
          dnf install -y git make gcc bison flex elfutils-devel openssl-devel rpm-build cpio hostname \
                         dwarves openssl perl rsync bc

      - name: Clone kernel source from your fork
        run: |
          # Clones the 'linux' repository from the GitHub user specified in the input
          git clone https://github.com/${{ github.event.inputs.fork_owner }}/linux.git
          cd linux
          # Checks out the specific branch from your fork
          git checkout ${{ github.event.inputs.branch_name }}
          echo "Successfully cloned and checked out ${{ github.event.inputs.branch_name }} from ${{ github.event.inputs.fork_owner }}/linux"

      - name: Configure Kernel
        run: |
          cd linux
          # Use 'make defconfig' to create a standard, default configuration
          # that is compatible with the upstream source code.
          make defconfig
          echo "Created default kernel configuration."

          # Now, apply your specific customizations
          echo "Enabling AMDGPU for SI cards and disabling radeon..."
          scripts/config --enable CONFIG_DRM_AMDGPU_SI
          scripts/config --disable CONFIG_DRM_RADEON_SI_SUPPORT
          echo "Kernel configuration updated."

      - name: Build kernel RPM packages
        run: |
          cd linux
          # Build the kernel and package it as an RPM.
          # The -j$(nproc) flag uses all available CPU cores to speed up the build.
          make -j$(nproc) binrpm-pkg

      - name: Upload kernel artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fedora-42-kernel-rpms-from-fork
          # The built RPMs will be in the rpmbuild directory created by the make command
          # The user running the build inside the container is root.
          path: /root/rpmbuild/RPMS/x86_64/
