name: Build Fedora 42 Kernel from Fork

on:
  workflow_dispatch:
    inputs:
      fork_owner:
        description: 'Your GitHub username or organization that owns the fork'
        required: true
        default: 'torvalds' # The default upstream kernel repository owner
      branch_name:
        description: 'The branch to build from your fork'
        required: true
        default: 'master' # The default upstream kernel branch

jobs:
  build:
    runs-on: ubuntu-latest
    container: fedora:42
    steps:
      - name: Install Build Dependencies
        run: |
          # CORRECTED: Added 'hostname' package to the list of dependencies.
          # Install all necessary tools for kernel compilation, including git, make, gcc, and others.
          dnf install -y git fedpkg fedora-packager rpmdevtools ncurses-devel pesign grubby \
                         make gcc bison flex elfutils-libelf-devel openssl-devel rpm-build cpio hostname

      - name: Clone kernel source from your fork
        run: |
          # Clones the 'linux' repository from the GitHub user specified in the input
          git clone https://github.com/${{ github.event.inputs.fork_owner }}/linux.git
          cd linux
          # Checks out the specific branch from your fork
          git checkout ${{ github.event.inputs.branch_name }}
          echo "Successfully cloned and checked out ${{ github.event.inputs.branch_name }} from ${{ github.event.inputs.fork_owner }}/linux"

      - name: Get Official Fedora Kernel Config
        run: |
          # Download the official Fedora kernel source package to get its configuration
          dnf download --source kernel
          # Create a temporary directory to safely extract the SRPM contents
          mkdir srpm_contents
          cd srpm_contents
          # Extract the entire SRPM content into the temporary directory
          rpm2cpio ../kernel-*.src.rpm | cpio -idmv
          # Use the correct filename 'kernel-x86_64-fedora.config'
          cp kernel-x86_64-fedora.config ../linux/.config
          cd ..
          echo "Copied official Fedora kernel config to the build directory."

      - name: Configure Kernel
        run: |
          cd linux
          # 'make olddefconfig' updates the .config file based on the source code,
          # preserving the settings from the official Fedora config where possible.
          make olddefconfig

          # Enable AMDGPU for Southern Islands (SI) and disable the old radeon driver
          echo "Enabling AMDGPU for SI cards and disabling radeon..."
          scripts/config --enable CONFIG_DRM_AMDGPU_SI
          scripts/config --disable CONFIG_DRM_RADEON_SI_SUPPORT
          echo "Kernel configuration updated."

      - name: Build kernel RPM packages
        run: |
          cd linux
          # Build the kernel and package it as an RPM.
          # The -j$(nproc) flag uses all available CPU cores to speed up the build.
          make -j$(nproc) binrpm-pkg

      - name: Upload kernel artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fedora-42-kernel-rpms-from-fork
          # The built RPMs will be in the rpmbuild directory created by the make command
          # The user running the build inside the container is root.
          path: /root/rpmbuild/RPMS/x86_64/

